<a href="https://colab.research.google.com/github/jackielyn-cabug/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Assignment_5_Matrix_Operation_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than  (3,3) . In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

In [56]:
A = np.array([
    [9,8,1],
    [4,7,1],
    [3,5,1]
])
B = np.array([
    [9,11,6],
    [4,1,10],
    [5,7,8]
])
C = np.array([
    [12,15,14],
    [10,17,11],
    [11,10,11]
])
D = np.array([
    [12,15],
    [10,17],
    [11,12],
])


## 6 MATRIX MULTIPLICATION PROPERTIES

### **Dimension Property**
##### In matrix multiplication, the product of m × n matrix and n×a matrix is the m× a matrix.


In [61]:
(A.T * B).T

array([[81, 32,  5],
       [44,  7,  7],
       [18, 50,  8]])

In [62]:
np.multiply(A,B)

array([[81, 88,  6],
       [16,  7, 10],
       [15, 35,  8]])

### **Commutative Property**
##### The matrix multiplication is not commutative.Assume that, if A and B are the two 2×2 matrices (AB ≠ BA),but, when the matrices are multiplied in this order, will be 3×3, not 2×2. 
## A × B = B × A

In [63]:
CP1 = A*B
CP1

array([[81, 88,  6],
       [16,  7, 10],
       [15, 35,  8]])

In [64]:
CP2 = B*A
CP2

array([[81, 88,  6],
       [16,  7, 10],
       [15, 35,  8]])

In [65]:
CP1 == CP2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [66]:
np.array_equal(CP1, CP2)

True

### **Associative Property**
##### If A, B and C are the three matrices, the associative property of matrix multiplication states that,
## A × (B × C)  = (A × B) × C 


In [67]:
AP1 = A*(B*C)
AP1

array([[ 972, 1320,   84],
       [ 160,  119,  110],
       [ 165,  350,   88]])

In [68]:
AP2 = (A*B)*C
AP2

array([[ 972, 1320,   84],
       [ 160,  119,  110],
       [ 165,  350,   88]])

In [69]:
AP1 == AP2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [70]:
np.array_equal(AP1, AP2)

True

### **Distributive Property**
##### Its distributive qualities come into the equation when combined with another arithmetic operation, such as addition or subtraction. In other terms, we use the distributive property to simplify issues when adding or subtracting matrices is a factor in the matrix multiplication. So the operation would be:
## A × (B + C)  = (A × B) + (A × C)

In [71]:
DP1 = A*(B+C)
DP1

array([[189, 208,  20],
       [ 56, 126,  21],
       [ 48,  85,  19]])

In [72]:
DP2 = (A*B)+(A*C)
DP2

array([[189, 208,  20],
       [ 56, 126,  21],
       [ 48,  85,  19]])

In [73]:
DP1 == DP2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [74]:
np.array_equal(DP1, DP2)

True

### **Multiplication by Zero**
##### If a matrix is multiplied by a zero matrix, the result matrix is a zero matrix.
## A × 0 = 0 × A = 0

In [75]:
MBZ1 = A*(np.zeros(3))
MBZ1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [76]:
MBZ2 = (np.zeros(3))*A
MBZ2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [77]:
MBZ1 == MBZ2 

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [78]:
np.array_equal(MBZ1, MBZ2)

True

### **Multiplicative Identity of Integer**
##### Similar to multiplying a matrix by the zero matrix, multiplying a matrix by the identity matrix yields the same result: the original matrix being multiplied by the identity matrix.In other words, multiplying a non-identity matrix by an identity matrix always gives the non-identity matrix, as follows:
## A × 1 = 1 × A = A


In [79]:
MIBI1 = A*(np.ones(3))
MIBI1

array([[9., 8., 1.],
       [4., 7., 1.],
       [3., 5., 1.]])

In [80]:
MIBI2 = (np.ones(3))*A
MIBI2

array([[9., 8., 1.],
       [4., 7., 1.],
       [3., 5., 1.]])

In [81]:
MIBI1 == MIBI2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [82]:
np.array_equal(MIBI1, MIBI2)

True