<a href="https://colab.research.google.com/github/jackielyn-cabug/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Assignment_3_Matrix_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Task 1

Create a function named mat_desc() that througouhly describes a matrix, it should:

* Displays the shape, size, and rank of the matrix.
* Displays whether the matrix is square or non-square.
* Displays whether the matrix is an empty matrix.
* Displays if the matrix is an identity, ones, or zeros matrix
* Use 5 sample matrices in which their shapes are not lower than (3,3) . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
## Function Area
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
from numpy.matrixlib.defmatrix import matrix
%matplotlib inline

In [ ]:
## Matrices Example
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]          
])
B = np.array([
    [9,4,3],
    [8,5,2],
    [7,6,1]          
])
C = np.array([
    [7,4,1,7,4],
    [8,5,2,8,5],
    [9,6,3,9,6]          
])
D = np.array([
    [9,8,7],
    [6,5,4],
    [3,2,1],
    [9,8,7]          
])
E = np.array([
    [1,3,6],
    [2,5,8],
    [4,7,9],
    [1,3,6],
])

In [ ]:
## Matrix Declarations
def mat_desc(matrix):
          try:
              is_empty = True if (matrix.size == 0) else False  #this command is to determine if the matrix is empty or not 
              is_square = True if matrix.shape[0] == matrix.shape[1] else False          #this command is to determine if the matrix square or non-square
              print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nSquare Matrix: {is_square}\nEmpty Matrix: {is_empty}\n')
          except TypeError:
              print("Empty Matrix")   

In [21]:
## Test Areas
mat_desc(A) # type the desired matrices listed above, if not just type "matrix"

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Shape:	(3, 3)
Rank:	2
Square Matrix: True
Empty Matrix: False



### Task 2
Create a function named mat_operations() that takes in two matrices a input parameters it should:

* Determines if the matrices are viable for operation and returns your own error message if they are not viable.
* Returns the sum of the matrices.
* Returns the differen of the matrices.
* Returns the element-wise multiplication of the matrices.
* Returns the element-wise division of the matrices.
* Use 5 sample matrices in which their shapes are not lower than (3,3) . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.d.

In [22]:
## Addition Operation
def mat_operations(addition):
    try:
      print("Sum of Matrices : ")
      ADD = A+B        # type the desired matrices and it listed above which A, B, C, D, and E.
      return (ADD)
    except ValueError:
      print("The matrices are not viable for operation.")
mat_operations(sum)

Sum of Matrices : 


array([[10,  6,  6],
       [12, 10,  8],
       [14, 14, 10]])

In [23]:
## Subtraction Operation
def mat_operation(subtraction):
  try:
    print("Difference of Matrix : ")
    SUB = A-B        # type the desired matrices and it listed above which A, B, C, D, and E.
    return (SUB)
  except ValueError:
    print("The matrices are not viable for operation.")
mat_operation(sum)

Difference of Matrix : 


array([[-8, -2,  0],
       [-4,  0,  4],
       [ 0,  2,  8]])

In [24]:
## Element-Wise Multiplication Operation
def mat_operation(element_wise_multiplication):
  try:
    print("Element-Wise Multiplication of Matrix : ")
    MULT = np.multiply(A,B)      # type the desired matrices and it listed above which A, B, C, D, and E.
    return (MULT)
  except ValueError:
    print("The matrices are not viable for operation.")
mat_operation(sum)

Element-Wise Multiplication of Matrix : 


array([[ 9,  8,  9],
       [32, 25, 12],
       [49, 48,  9]])

In [25]:
## Element-Wise Division Operation
def mat_operation(element_wise_division):
  try:
    print("Element-Wise Division of Matrix : ")
    DIV = np.divide(A,B)  # type the desired matrices and it listed above which A, B, C, D, and E.
    return (DIV)
  except ValueError:
    print("The matrices are not viable for operation.")
mat_operation(sum)

Element-Wise Division of Matrix : 


array([[0.11111111, 0.5       , 1.        ],
       [0.5       , 1.        , 3.        ],
       [1.        , 1.33333333, 9.        ]])